<style>
  .devzinho-page{position:relative;min-height:calc(100vh - 88px);padding:24px 38px 38px;overflow-x:clip;overflow-y:visible;}
  .devzinho-page:before{content:'';position:absolute;inset:0;z-index:-1;background:radial-gradient(circle at 78% 22%,rgba(140,215,226,.14),transparent 26%),linear-gradient(180deg,rgba(84,159,181,.11),rgba(4,66,113,.05));pointer-events:none;}
  .devzinho-layout{width:min(1180px,100%);margin:0 auto 56px;display:grid;grid-template-columns:225px minmax(0,1fr);gap:28px;align-items:stretch;}
  .devzinho-ia-title{grid-column:1/-1;justify-self:center;margin:0 0 -4px;padding:11px 42px;border-radius:23px;background:#022a56;box-shadow:0 9px 0 rgba(0,0,0,.14),0 5px 12px rgba(0,0,0,.20);font-family:'Pixelify Sans',monospace;font-size:29px;font-weight:600;letter-spacing:1px;color:#fff;}
  .history-panel{align-self:stretch;min-height:590px;padding:20px 16px;border:1px solid rgba(255,255,255,.18);border-radius:30px;background:linear-gradient(160deg,rgba(222,238,244,.19),rgba(54,120,149,.34));box-shadow:0 12px 28px rgba(0,30,56,.18),inset 0 1px 0 rgba(255,255,255,.13);backdrop-filter:blur(10px);}
  .history-panel__header{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:0 3px 14px;border-bottom:1px solid rgba(255,255,255,.18);}.history-panel__title{display:flex;align-items:center;gap:9px;margin:0;color:#fff;font-family:'Urbanist',sans-serif;font-size:20px;font-weight:800;}.history-panel__title svg{color:#dcecf4;}.history-clear{border:0;border-radius:9px;padding:6px 8px;background:rgba(2,42,86,.42);color:#eff8fb;font-family:'Urbanist',sans-serif;font-size:11px;font-weight:800;cursor:pointer;transition:background .2s;}.history-clear:hover{background:#022a56;}
  .history-help{margin:13px 3px 15px;color:rgba(238,249,252,.75);font-family:'Urbanist',sans-serif;font-size:12px;font-weight:600;line-height:1.35;}.history-list{display:flex;flex-direction:column;gap:10px;max-height:470px;overflow:auto;padding:0 2px 5px;}.history-empty{margin:38px 4px;color:rgba(238,249,252,.72);font-family:'Urbanist',sans-serif;font-size:13px;font-weight:700;line-height:1.45;text-align:center;}.history-card{width:100%;border:1px solid rgba(255,255,255,.14);border-radius:16px;padding:12px;background:rgba(2,42,86,.31);color:#fff;text-align:left;cursor:pointer;transition:transform .2s,background .2s;}.history-card:hover{background:rgba(2,42,86,.57);transform:translateY(-2px);}.history-card strong,.history-card span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}.history-card strong{font-family:'Urbanist',sans-serif;font-size:13px;font-weight:800;}.history-card span{margin-top:5px;color:rgba(229,243,248,.72);font-family:'Urbanist',sans-serif;font-size:12px;font-weight:600;}.history-card time{display:block;margin-top:7px;color:rgba(179,218,229,.9);font-family:'Urbanist',sans-serif;font-size:10px;font-weight:700;}
  .devzinho-chat{display:flex;min-width:0;flex-direction:column;gap:14px;min-height:665px;}.devzinho-hero{position:relative;display:flex;align-items:flex-start;justify-content:flex-end;min-height:285px;padding:0;margin-right:-42px;}.devzinho-welcome{display:flex;align-items:flex-start;justify-content:flex-end;gap:0;width:100%;max-width:100%;}.devzinho-welcome__bubble{position:relative;z-index:2;width:max-content;max-width:430px;margin:84px -64px 0 0;border-radius:24px;padding:15px 20px;background:#dce8f1;color:#07182d;box-shadow:0 6px 0 rgba(0,0,0,.17),0 4px 10px rgba(0,0,0,.16);font-family:'Urbanist',sans-serif;font-size:19px;font-weight:800;white-space:nowrap;}.devzinho-welcome__robot{position:relative;z-index:1;width:370px;height:285px;object-fit:contain;object-position:right top;filter:drop-shadow(0 10px 7px rgba(0,0,0,.16));}
  .chat-stage{display:flex;min-height:450px;flex:1;flex-direction:column;gap:17px;padding:2px 10px 4px;}.chat-log{display:flex;min-height:390px;max-height:560px;flex:1;flex-direction:column;justify-content:flex-start;gap:21px;overflow-y:auto;overflow-x:hidden;padding:12px 13px 18px;scroll-behavior:smooth;scrollbar-color:rgba(219,237,243,.75) rgba(2,42,86,.20);scrollbar-width:thin;}.chat-log::-webkit-scrollbar{width:8px;}.chat-log::-webkit-scrollbar-track{background:rgba(2,42,86,.17);border-radius:99px;}.chat-log::-webkit-scrollbar-thumb{border-radius:99px;background:rgba(219,237,243,.72);}.chat-row{display:flex;align-items:flex-end;gap:11px;max-width:100%;flex:0 0 auto;animation:devzinho-rise .28s ease-out;}.chat-row--user{justify-content:flex-end;margin-left:112px;}.chat-row--assistant{justify-content:flex-start;margin-right:68px;}.chat-bubble{position:relative;overflow-wrap:anywhere;border-radius:22px;padding:17px 21px;box-shadow:0 7px 0 rgba(0,0,0,.14),0 5px 14px rgba(0,0,0,.15);font-family:'Urbanist',sans-serif;font-size:18px;font-weight:800;line-height:1.42;white-space:pre-wrap;}.chat-bubble--user{max-width:520px;border-bottom-right-radius:7px;background:#022a56;color:#fff;}.chat-bubble--assistant{max-width:610px;border-bottom-left-radius:7px;background:#d9e8f3;color:#07182d;}.chat-bubble--user:after,.chat-bubble--assistant:after{content:'';position:absolute;bottom:-8px;width:18px;height:18px;transform:rotate(45deg);z-index:-1;}.chat-bubble--user:after{right:10px;background:#022a56;}.chat-bubble--assistant:after{left:10px;background:#d9e8f3;}.chat-quick-return{align-self:flex-start;margin:0 0 8px 59px;border:0;border-radius:999px;padding:9px 15px;background:#022a56;color:#fff;font-family:'Urbanist',sans-serif;font-size:13px;font-weight:800;box-shadow:0 4px 0 rgba(0,0,0,.14);cursor:pointer;}.chat-quick-return:hover{background:#0b568e;}
  .chat-avatar{flex:0 0 auto;width:48px;height:48px;border-radius:50%;display:grid;place-items:center;overflow:hidden;box-shadow:0 4px 11px rgba(0,0,0,.25);}.chat-avatar--devzinho{align-self:flex-end;background:rgba(221,237,242,.22);border:2px solid rgba(255,255,255,.42);}.chat-avatar--devzinho img{width:47px;height:57px;object-fit:contain;object-position:bottom;transform:translateY(4px);}.chat-avatar--user{background:linear-gradient(145deg,#c59b7b,#3c2a24);border:2px solid rgba(255,255,255,.55);color:#fff;font-family:'Urbanist',sans-serif;font-size:18px;font-weight:800;}
  .devzinho-status{display:flex;align-items:center;gap:7px;margin:0 0 0 59px;color:rgba(232,244,247,.80);font-family:'Urbanist',sans-serif;font-size:12px;font-weight:700;}.devzinho-status i{width:8px;height:8px;border-radius:50%;background:#61d0b5;box-shadow:0 0 8px #61d0b5;}.chat-composer{display:flex;align-items:center;gap:13px;width:100%;border-radius:34px;padding:7px 12px 7px 25px;background:#dce8f1;box-shadow:0 6px 0 rgba(0,0,0,.15),0 5px 12px rgba(0,0,0,.16);}.chat-composer input{min-width:0;flex:1;border:0;outline:0;background:transparent;color:#10233a;font-family:'Urbanist',sans-serif;font-size:16px;font-weight:600;padding:12px 0;}.chat-composer input::placeholder{color:#718596;}.chat-send,.chat-mic{width:42px;height:42px;border:0;background:transparent;color:#041c37;display:grid;place-items:center;cursor:pointer;border-radius:50%;transition:background .2s,transform .2s;}.chat-send:hover,.chat-mic:hover{background:rgba(2,42,86,.12);transform:translateY(-2px);}.chat-send svg{transform:rotate(-20deg);}.chat-quick-actions{display:flex;justify-content:center;gap:9px;margin:2px 0 0;}.chat-quick-actions button{border:1px solid rgba(255,255,255,.17);border-radius:999px;padding:7px 13px;background:rgba(2,42,86,.35);color:#e5f1f5;font-family:'Urbanist',sans-serif;font-size:12px;font-weight:700;cursor:pointer;transition:background .2s,transform .2s;}.chat-quick-actions button:hover{background:rgba(2,42,86,.62);transform:translateY(-2px);}
  .history-modal{position:fixed;inset:0;z-index:1000;display:none;align-items:center;justify-content:center;padding:20px;background:rgba(0,20,42,.62);backdrop-filter:blur(7px);}.history-modal.is-open{display:flex;}.history-modal__box{width:min(630px,100%);max-height:min(700px,86vh);display:flex;flex-direction:column;border:1px solid rgba(255,255,255,.18);border-radius:26px;background:#0b4776;box-shadow:0 25px 55px rgba(0,0,0,.45);overflow:hidden;}.history-modal__top{display:flex;align-items:center;justify-content:space-between;padding:18px 22px;border-bottom:1px solid rgba(255,255,255,.14);color:#fff;font-family:'Urbanist',sans-serif;}.history-modal__top h2{margin:0;font-size:20px;font-weight:800;}.history-modal__top button{width:32px;height:32px;border:0;border-radius:50%;background:rgba(255,255,255,.14);color:#fff;font-size:22px;cursor:pointer;}.history-modal__body{display:flex;flex-direction:column;gap:14px;overflow-y:auto;padding:20px;}.history-modal__message{max-width:85%;border-radius:17px;padding:12px 15px;font-family:'Urbanist',sans-serif;font-size:14px;font-weight:700;line-height:1.4;}.history-modal__message--user{align-self:flex-end;background:#022a56;color:#fff;}.history-modal__message--assistant{align-self:flex-start;background:#d9e8f3;color:#07182d;}
  .devzinho-typing{display:flex;gap:5px;align-items:center;min-height:22px;}.devzinho-typing i{width:7px;height:7px;border-radius:50%;background:#527080;animation:devzinho-dot 1s infinite ease-in-out;}.devzinho-typing i:nth-child(2){animation-delay:.14s;}.devzinho-typing i:nth-child(3){animation-delay:.28s;}@keyframes devzinho-dot{0%,80%,100%{transform:translateY(0);opacity:.4}40%{transform:translateY(-4px);opacity:1}}@keyframes devzinho-rise{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}
  @media(max-width:1050px){.devzinho-layout{grid-template-columns:190px minmax(0,1fr);gap:18px;}.devzinho-hero{min-height:230px;margin-right:-18px;}.devzinho-welcome__robot{width:282px;height:230px;}.devzinho-welcome__bubble{width:max-content;margin:63px -47px 0 0;font-size:16px;}.chat-row--user{margin-left:75px;}.chat-row--assistant{margin-right:35px;}.chat-bubble--assistant{max-width:560px;}}
  @media(max-width:780px){.devzinho-page{padding:20px 16px 30px;}.devzinho-layout{display:flex;flex-direction:column;gap:18px;}.devzinho-ia-title{align-self:center;font-size:24px;padding:10px 30px;}.history-panel{order:3;min-height:auto;}.history-list{max-height:215px;}.devzinho-chat{min-height:540px;}.devzinho-hero{min-height:165px;margin-right:-10px;padding-right:0;}.devzinho-welcome__robot{width:170px;height:165px;}.devzinho-welcome__bubble{max-width:calc(100vw - 195px);margin-top:42px;font-size:13px;white-space:normal;}.chat-stage{min-height:340px;padding:0;}.chat-log{min-height:300px;max-height:480px;padding:10px 4px 15px;}.chat-row--user{margin-left:17px;}.chat-row--assistant{margin-right:17px;}.chat-bubble{font-size:15px;padding:14px 16px;}.chat-avatar{width:38px;height:38px;}.chat-avatar--devzinho img{width:38px;height:48px;}.chat-composer{padding-left:15px;}.chat-composer input{font-size:14px;}.chat-quick-actions{flex-wrap:wrap;}.devzinho-status{margin-left:50px;}.chat-quick-return{margin-left:50px;}.page-footer{margin-left:0!important;margin-right:0!important;}}
</style>

<section class="devzinho-page" aria-label="Conversa com o Devzinho">
  <div class="devzinho-layout">
    <h1 class="devzinho-ia-title">Nossa IA</h1>

    <aside class="history-panel" aria-label="Histórico de conversas">
      <div class="history-panel__header">
        <h2 class="history-panel__title"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 3v5h5"></path><path d="M3.05 13a9 9 0 1 0 2.1-5.7L3 8"></path><path d="M12 7v5l3 2"></path></svg>Histórico</h2>
        <button id="history-clear" class="history-clear" type="button">Limpar</button>
      </div>
      <p class="history-help">As conversas anteriores ficam aqui. Ao voltar para a IA, uma conversa nova e limpa é aberta.</p>
      <div id="devzinho-history-list" class="history-list"></div>
    </aside>

    <div class="devzinho-chat">
      <div class="devzinho-hero" aria-hidden="true">
        <div class="devzinho-welcome">
          <p class="devzinho-welcome__bubble">Olá! Sou o Devzinho, precisa de ajuda?</p>
          <img class="devzinho-welcome__robot" src="<?= ASSETS ?>/images/devzinho-ola.png" alt=""/>
        </div>
      </div>

      <div class="chat-stage">
        <div id="devzinho-chat-log" class="chat-log" aria-live="polite">
          <div class="chat-row chat-row--user"><div class="chat-bubble chat-bubble--user">Olá Devzinho! Como posso acessar meus projetos postados?</div><div class="chat-avatar chat-avatar--user" aria-label="Você">U</div></div>
          <div class="chat-row chat-row--assistant"><div class="chat-avatar chat-avatar--devzinho"><img src="<?= ASSETS ?>/images/devzinho-sentado.png" alt="Devzinho"/></div><div class="chat-bubble chat-bubble--assistant">Essa é uma ótima pergunta! Para ver os seus projetos, entre na aba <strong>“Meus projetos”</strong> no menu lateral. Lá você pode criar pastas, editar códigos, salvar projetos e organizar seus arquivos.</div></div>
        </div>
        <p class="devzinho-status"><i></i>Devzinho está pronto para ajudar com Architech e programação.</p>
        <form id="devzinho-form" class="chat-composer" autocomplete="off">
          <input id="devzinho-input" type="text" maxlength="500" placeholder="Relate sua dúvida/problema encontrado(a) para o Devzinho" aria-label="Escreva sua mensagem para o Devzinho"/>
          <button class="chat-mic" type="button" title="Entrada por voz em breve" aria-label="Entrada por voz"><svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="2" width="6" height="12" rx="3"></rect><path d="M5 10a7 7 0 0 0 14 0M12 19v3M8 22h8"></path></svg></button>
          <button class="chat-send" type="submit" aria-label="Enviar mensagem"><svg width="27" height="27" viewBox="0 0 24 24" fill="currentColor"><path d="M3.4 2.6 22 11.2c.9.4.9 1.2 0 1.6L3.4 21.4c-.7.3-1.4-.3-1.2-1L5 13l8-1-8-1-2.8-7.4c-.2-.7.5-1.3 1.2-1Z"></path></svg></button>
        </form>
        <div class="chat-quick-actions" aria-label="Perguntas sugeridas"><button type="button" data-question="Como criar um projeto?">Criar projeto</button><button type="button" data-question="Como usar o editor de código?">Usar editor</button><button type="button" data-question="Explique responsividade em CSS">Dica de CSS</button></div>
      </div>
    </div>
  </div>
</section>

<div id="history-modal" class="history-modal" role="dialog" aria-modal="true" aria-labelledby="history-modal-title">
  <div class="history-modal__box"><div class="history-modal__top"><h2 id="history-modal-title">Conversa anterior</h2><button id="history-modal-close" type="button" aria-label="Fechar histórico">×</button></div><div id="history-modal-body" class="history-modal__body"></div></div>
</div>

<footer class="page-footer anim-footer" style="margin:0 38px 20px;"><div class="footer-card"><div class="footer-grid">
  <div style="display:flex;flex-direction:column;align-items:center;"><img style="width:92px;height:92px;object-fit:cover;" src="<?= ASSETS ?>/images/c244a778-6383-491d-b2f6-58d02d819c9e-1.png" alt="Architech"/><span class="font-pixelify" style="margin-top:4px;font-size:20px;font-weight:600;letter-spacing:2.2px;color:#fff;white-space:nowrap;text-shadow:0 4px 4px #00000040;">ARCHITECH</span></div>
  <img style="width:9px;height:118px;align-self:center;" src="<?= ASSETS ?>/images/line-1.svg" alt=""/>
  <div style="display:flex;flex-direction:column;align-items:center;gap:12px;"><div style="display:flex;align-items:center;border-radius:20px;padding:12px 24px;background:#ffffff1a;box-shadow:0 4px 4px #00000033;"><a href="<?= BASE_URL ?>/" class="nav-btn">Principal</a><a href="<?= BASE_URL ?>/exercicios" class="nav-btn">Exercícios</a><a href="<?= BASE_URL ?>/sobre" class="nav-btn">Sobre</a></div><p class="font-urbanist" style="font-size:14px;font-weight:700;letter-spacing:1.54px;color:#fff;text-shadow:0 4px 4px #00000040;">© Architech. Todos os direitos reservados.</p></div>
  <div style="display:flex;flex-direction:column;gap:8px;"><div style="display:flex;align-items:center;gap:28px;"><a href="#" class="social-link"><img style="width:47px;height:47px;" src="<?= ASSETS ?>/images/mdi-twitter.svg" alt="Twitter"/></a><a href="#" class="social-link"><img style="width:47px;height:50px;" src="<?= ASSETS ?>/images/formkit-instagram.svg" alt="Instagram"/></a><a href="#" class="social-link"><img style="width:45px;height:48px;" src="<?= ASSETS ?>/images/mdi-github.svg" alt="GitHub"/></a></div><p class="font-urbanist" style="font-size:14px;font-weight:700;letter-spacing:1.54px;color:#fff;text-shadow:0 4px 4px #00000040;">Suporte: architech.dev@gmail.com</p></div>
</div></div></footer>

<script src="<?= ASSETS ?>/js/devzinho.js"></script>
